name: yalecaigo
description: Aplicación Flutter para solicitud de servicios de acompañamiento.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  flutter_map: ^7.0.2
  flutter_secure_storage: ^9.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
