name: yalecaigo
description: Aplicación Flutter para solicitud de servicios de acompañamiento.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  dio: ^5.10.0
  flutter_map: ^8.3.1
  flutter_secure_storage: ^10.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo_mark.png
    - assets/branding/logo_mark_mono.png
    - assets/branding/app_icon.png
    - assets/branding/app_icon_light.png
    - assets/branding/opentic_logo.png
